major_minor_ver:
  - 9.2
  - 10.0
  - 10.1
  - 10.2
  - 11.0
  - 11.1
  - 11.2

cuda_compiler_version:                  # [linux64]
  - None                                # [linux64]
docker_image:                           # [linux64]
  - condaforge/linux-anvil-cos7-x86_64  # [linux64]
